steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/transnational-aqms:$BUILD_ID",
        "-f",
        "deployment/Dockerfile",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/transnational-aqms:$BUILD_ID"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "aqms-bangladesh"
      - "--image"
      - "gcr.io/$PROJECT_ID/transnational-aqms:$BUILD_ID"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "COUNTRY_CODE=BD,ENVIRONMENT=production"
      - "--memory"
      - "1Gi"
      - "--cpu"
      - "1"
      - "--max-instances"
      - "10"
      - "--min-instances"
      - "0"
      - "--timeout"
      - "300"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "aqms-india"
      - "--image"
      - "gcr.io/$PROJECT_ID/transnational-aqms:$BUILD_ID"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "COUNTRY_CODE=IN,ENVIRONMENT=production"
      - "--memory"
      - "1Gi"
      - "--cpu"
      - "1"
      - "--max-instances"
      - "10"
      - "--min-instances"
      - "0"
      - "--timeout"
      - "300"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "aqms-orchestrator"
      - "--image"
      - "gcr.io/$PROJECT_ID/transnational-aqms:$BUILD_ID"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "SERVICE_TYPE=orchestrator,ENVIRONMENT=production"
      - "--memory"
      - "2Gi"
      - "--cpu"
      - "2"
      - "--max-instances"
      - "10"
      - "--min-instances"
      - "0"
      - "--timeout"
      - "600"

images:
  - "gcr.io/$PROJECT_ID/transnational-aqms:$BUILD_ID"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

timeout: "1200s"
